<?php


define ('DEFAULT_CSV_SEPARATOR', ',');

define ('FREE_COMMISSION_PRIVATE_USER_WITHDRAW_AMOUNT', 1000);
define ('FREE_COMMISSION_PRIVATE_USER_WITHDRAW_CURRENCY', 'EUR');
define ('FREE_COMMISSION_PRIVATE_WITHDRAW_OPERATION_COUNT_LIMIT', 3);
define ('FREE_COMMISSION_PERIOD_IN_DAYS', 7);

define ('COMMISSION_PRIVATE_WITHDRAW', 0.003);
define ('COMMISSION_PRIVATE_DEPOSIT', 0.0003);
define ('COMMISSION_BUSINESS_WITHDRAW', 0.005);
define ('COMMISSION_BUSINESS_DEPOSIT', 0.0003);

define ('COMMISSION_ROUNDING_PRECISION', 2);
define ('CURRENCIES_WITH_NO_DECIMALS',
['BIF', 'CLP', 'DJF', 'GNF', 'ISK', 'JPY', 'KMF', 'KRW', 'PYG', 'RWF', 'UGX', 'UYI', 'VND', 'VUV', 'XAF', 'XOF', 'XPF']
);