<?php


define ('DEFAULT_CSV_SEPARATOR', ',');

define ('FREE_COMMISSION_PRIVATE_USER_WITHDRAW_AMOUNT', 1000);
define ('FREE_COMMISSION_PRIVATE_USER_WITHDRAW_CURRENCY', 'EUR');
define ('FREE_COMMISSION_PRIVATE_WITHDRAW_OPERATION_COUNT_LIMIT', 3);
define ('FREE_COMMISSION_PERIOD_IN_DAYS', 7);

define ('COMMISSION_PRIVATE_WITHDRAW', 0.03);
define ('COMMISSION_PRIVATE_DEPOSIT', 0.03);
define ('COMMISSION_BUSINESS_WITHDRAW', 0.05);
define ('COMMISSION_BUSINESS_DEPOSIT', 0.03);

define ('COMMISSION_ROUNDING_PRECISION', 2);